apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: django-web
  name: django-web
spec:
  replicas: 1
  revisionHistoryLimit: 10
  selector:
    matchLabels:
      app: django-web
  template:
    metadata:
      labels:
        app: django-web
    spec:
      containers:
      - name: django-web
        image: northamerica-northeast2-docker.pkg.dev/project-4d782c37-789b-47ab-97d/my-registry/django-web:latest
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: 8080
        env:
        - name: APPTYPE
          value: "GKE"
        - name: DATABASE_HOST
          value: pg-release-postgresql
        - name: DATABASE_PASSWORD
          value: "admin"
        
status:
  availableReplicas: 1
  readyReplicas: 1
  replicas: 1
  updatedReplicas: 1
